#
# For licensing see accompanying LICENSE file.
# Copyright (C) 2020 Apple Inc. All Rights Reserved.
#

import trainers.default as default
import trainers.ensemble as ensemble
import trainers.eval_one_dim_subspaces as eval_one_dim_subspaces
import trainers.eval_one_dim_subspaces_multiclass_metric as eval_one_dim_subspaces_multiclass_metric
import trainers.eval_one_dim_subspaces_multigpu as eval_one_dim_subspaces_multigpu
import trainers.eval_one_dim_subspaces_stochastic as eval_one_dim_subspaces_stochastic
import trainers.eval_single_varied_threshold as eval_single_varied_threshold
import trainers.eval_weighted_single_one_v_all as eval_weighted_single_one_v_all
import trainers.linestats_swa as linestats_swa
import trainers.simplex_ensembles as simplex_ensembles
import trainers.swa_endpoint_ensembles as swa_endpoint_ensembles
import trainers.swag as swag
import trainers.train_one_dim_subspaces as train_one_dim_subspaces
import trainers.train_one_dim_subspaces_stochastic as train_one_dim_subspaces_stochastic
import trainers.train_simplexes as train_simplexes
import trainers.train_single_one_v_all as train_single_one_v_all
import trainers.train_single_one_v_all_stochastic as train_single_one_v_all_stochastic
import trainers.train_weighted_single_one_v_all as train_weighted_single_one_v_all
